//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U3A_Attendance_Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class Location
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public Location()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
            this.Sessions = new HashSet<Session>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private string _room;
        public  string Room 
		{ 
			get
			{ 
				return _room; 
			} 
			set
			{
				_room = value;
				ObjectPropertyChanged("Room");
			}
		}
    	private System.Guid _venueid;
        public  System.Guid VenueId 
		{ 
			get
			{ 
				return _venueid; 
			} 
			set
			{
				_venueid = value;
				ObjectPropertyChanged("VenueId");
			}
		}
    
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
