
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace U3A_Attendance_Model
{

using System;
    using System.Collections.Generic;
    
using System.ComponentModel;
internal partial class Member
{
	

	partial void ObjectPropertyChanged(string propertyName);


    public Member()
    {

        this.Attendances = new HashSet<Attendance>();

    }


	private System.Guid _u3aid;
    public  System.Guid U3AId 
		{ 
			get
			{ 
				return _u3aid; 
			} 
			set
			{
				_u3aid = value;
				ObjectPropertyChanged("U3AId");
			}
		}

	private int _memberid;
    public  int MemberId 
		{ 
			get
			{ 
				return _memberid; 
			} 
			set
			{
				_memberid = value;
				ObjectPropertyChanged("MemberId");
			}
		}



    public virtual ICollection<Attendance> Attendances { get; set; }

    public virtual U3A U3A { get; set; }

}

}
