
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace U3A_Attendance_Model
{

using System;
    using System.Collections.Generic;
    
using System.ComponentModel;
internal partial class Venue
{
	

	partial void ObjectPropertyChanged(string propertyName);


    public Venue()
    {

        this.Locations = new HashSet<Location>();

    }


	private System.Guid _id;
    public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}

	private string _name;
    public  string Name 
		{ 
			get
			{ 
				return _name; 
			} 
			set
			{
				_name = value;
				ObjectPropertyChanged("Name");
			}
		}

	private string _address;
    public  string Address 
		{ 
			get
			{ 
				return _address; 
			} 
			set
			{
				_address = value;
				ObjectPropertyChanged("Address");
			}
		}

	private string _codeid;
    public  string CodeId 
		{ 
			get
			{ 
				return _codeid; 
			} 
			set
			{
				_codeid = value;
				ObjectPropertyChanged("CodeId");
			}
		}

	private System.Guid _suburbid;
    public  System.Guid SuburbId 
		{ 
			get
			{ 
				return _suburbid; 
			} 
			set
			{
				_suburbid = value;
				ObjectPropertyChanged("SuburbId");
			}
		}



    public virtual ICollection<Location> Locations { get; set; }

    public virtual Suburb Suburb { get; set; }

}

}
