//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U3A_Attendance_Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    internal partial class CourseDescription
    {
    	
    	partial void ObjectPropertyChanged(string propertyName);
    
        public CourseDescription()
        {
            this.CourseInstances = new HashSet<CourseInstance>();
        }
    
    	private System.Guid _id;
        public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}
    	private int _coursenumber;
        public  int CourseNumber 
		{ 
			get
			{ 
				return _coursenumber; 
			} 
			set
			{
				_coursenumber = value;
				ObjectPropertyChanged("CourseNumber");
			}
		}
    	private string _title;
        public  string Title 
		{ 
			get
			{ 
				return _title; 
			} 
			set
			{
				_title = value;
				ObjectPropertyChanged("Title");
			}
		}
    	private string _description;
        public  string Description 
		{ 
			get
			{ 
				return _description; 
			} 
			set
			{
				_description = value;
				ObjectPropertyChanged("Description");
			}
		}
    	private System.Guid _u3aid;
        public  System.Guid U3AId 
		{ 
			get
			{ 
				return _u3aid; 
			} 
			set
			{
				_u3aid = value;
				ObjectPropertyChanged("U3AId");
			}
		}
    
        public virtual ICollection<CourseInstance> CourseInstances { get; set; }
        public virtual U3A U3A { get; set; }
    }
}
