//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U3A_Attendance_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class U3AAttendanceEntities : DbContext
    {
        public U3AAttendanceEntities()
            : base("name=U3AAttendanceEntities")
        {
    		Attendances = Set<Attendance>();	
    		Coordinators = Set<Coordinator>();	
    		CourseDescriptions = Set<CourseDescription>();	
    		CourseInstances = Set<CourseInstance>();	
    		Locations = Set<Location>();	
    		Members = Set<Member>();	
    		Regions = Set<Region>();	
    		Sessions = Set<Session>();	
    		Suburbs = Set<Suburb>();	
    		U3A = Set<U3A>();	
    		Venues = Set<Venue>();	
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal DbSet<Attendance> Attendances { get; set; }
        internal DbSet<Coordinator> Coordinators { get; set; }
        internal DbSet<CourseDescription> CourseDescriptions { get; set; }
        internal DbSet<CourseInstance> CourseInstances { get; set; }
        internal DbSet<Location> Locations { get; set; }
        internal DbSet<Member> Members { get; set; }
        internal DbSet<Region> Regions { get; set; }
        internal DbSet<Session> Sessions { get; set; }
        internal DbSet<Suburb> Suburbs { get; set; }
        internal DbSet<U3A> U3A { get; set; }
        internal DbSet<Venue> Venues { get; set; }
    }
}
