
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace U3A_Attendance_Model
{

using System;
    using System.Collections.Generic;
    
using System.ComponentModel;
internal partial class Session
{
	

	partial void ObjectPropertyChanged(string propertyName);


    public Session()
    {

        this.Attendances = new HashSet<Attendance>();

    }


	private System.Guid _id;
    public  System.Guid Id 
		{ 
			get
			{ 
				return _id; 
			} 
			set
			{
				_id = value;
				ObjectPropertyChanged("Id");
			}
		}

	private System.DateTime _date;
    public  System.DateTime Date 
		{ 
			get
			{ 
				return _date; 
			} 
			set
			{
				_date = value;
				ObjectPropertyChanged("Date");
			}
		}

	private System.Guid _courseinstanceid;
    public  System.Guid CourseInstanceId 
		{ 
			get
			{ 
				return _courseinstanceid; 
			} 
			set
			{
				_courseinstanceid = value;
				ObjectPropertyChanged("CourseInstanceId");
			}
		}

	private System.Guid _locationid;
    public  System.Guid LocationId 
		{ 
			get
			{ 
				return _locationid; 
			} 
			set
			{
				_locationid = value;
				ObjectPropertyChanged("LocationId");
			}
		}

	private int _visitorcount;
    public  int VisitorCount 
		{ 
			get
			{ 
				return _visitorcount; 
			} 
			set
			{
				_visitorcount = value;
				ObjectPropertyChanged("VisitorCount");
			}
		}



    public virtual ICollection<Attendance> Attendances { get; set; }

    public virtual Location Location { get; set; }

    public virtual CourseInstance CourseInstance { get; set; }

}

}
